[package]
name = "ex16_une_lettre_sur_deux"
version = "0.1.0"
authors = ["Louis Cherel <cherel.louis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
